import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import PersistStoreProvider from './lib/features/PersistStoreProvider'
import NavBar from './ui/nav-bar'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PersistStoreProvider>
          <div className="relative h-screen w-screen overflow-hidden">
            <div className="fixed w-full">
              <NavBar />
            </div>
            <div className="pt-12 overflow-y-hidden sm:pt-14">
              {children}
            </div>
          </div>
        </PersistStoreProvider>
      </body>
    </html>
  )
}

