import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NavBar from './ui/nav-bar'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="fixed w-full">
            <NavBar />
          </div>
          <div>notification</div>
          <div className="grow pt-6 h-screen overflow-y-hidden">{children}</div>
        </div>
      </body>
    </html>
  )
}

